#!/bin/bash

# 如果设置了 WWWUSER 环境变量，同步 uid
if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# 确保 Composer 缓存目录可写
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

# 有参数时直接以 sail 用户执行命令，否则启动 Supervisor
if [ $# -gt 0 ]; then
    exec gosu sail "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
